version: "3.9"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_CONSULTANT_USERNAME=${BOT_CONSULTANT_USERNAME}
      - OPENAI_ORGANIZATION_ID=${OPENAI_ORGANIZATION_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MIN_PUBLISH_INTERVAL=${MIN_PUBLISH_INTERVAL}
      - PUBLISH_INTERVAL=${PUBLISH_INTERVAL}
      - USER_MONTH_VACANCY_LIMIT=${USER_MONTH_VACANCY_LIMIT}
      - COMPANY_MONTH_VACANCY_LIMIT=${COMPANY_MONTH_VACANCY_LIMIT}
      - DB_SSL_ENABLED=${DB_SSL_ENABLED}
      - BOT_CONTACTS=${BOT_CONTACTS}
      - PUBLISH_CONFIG=${PUBLISH_CONFIG}
      - DAILY_VACANCY_LIMIT=${DAILY_VACANCY_LIMIT}
